class Challenge < ActiveRecord::Base
	before_save { self.description = description.titleize }
	has_and_belongs_to_many :users
	default_scope -> { order('created_at DESC') }

	def self.all_types
		[	
			"pushups",
			"running",
			"pie-eating",
			"donkey racing",
			"yak shaving",
			"karate",
			"karaoke",
			"knitting",
			"horse back riding",
			"a chili cookoff",
			"jello wrestling",
			"carpet cleaning",
			"chess",
			"checkers",
			"scrabble",
			"jenga",
			"lawnmowing",
			"blood donation",
			"looking like steve jobs",
			"coffee brewing",
			"body hiding",
			"water filtration",
			"pasta making",
			"pea shooting",
			"moustache growing",
			"pokemon battling",
			"air guitar",
			"rock paper scissors",
			"curling",
			"jamaican bobsledding",
			"cheese rolling",
			"extreme ironing",
			"javelin",
			"shoelace tying",
			"sheep counting",
			"spin the bottle",
			"hot dog eating",
			"pumpkin catapaulting",
			"ostrich racing",
			"yodeling",
			"tug o war",
			"table tennis",
			"don't spill the beans",
			"cat herding",
			"being the ugliest",
			"arm wrestling",
			"fly fishing",
			"spelling",
			"chest hair removal",
			"fire breathing",
			"lego tower building",
			"falcon training",
			"having the most hobbit-like feet",
			"billboard painting",
			"bird watching",
			"bluetooth device ownership",
			"janitorial services",
			"self-tattooing",
			"being the worst",
			"having the most elaborate neck tattoo",
			"cockfighting",
			"wurst-making",
			"fish tossing",
			"having the longest nose hairs",
			"being a beautiful young lady and a old ugly lady all at once",
			"toenail growing",
			"mohawk ownership",
			"navel-gazing",
			"designer sneaker ownership",
			"having the biggest 80s rock hair",
			"being the most offensive",
			"having the most heinous B.O.",
			"being a diversity hire",
			"unibrow cultivation",
			"flamingo figurine collecting",
			"bee wrangling",
			"yelling the loudest at computers",
			"identifying the most with Dilbert",
			"sushi rolling",
			"dodgeball",
			"sportsball",
			"handegg",
			"googling",
			"myspace profile updating",
			"emoji memorizaition",
			"slapfighting",
			"having t-rex arms",
			"vinyl collecting",
			"bicycle repair",
			"breaking the 5 second rule",
			"pinata bashing",
			"being the sassiest cat",
			"having the biggest glasses",
			"being the most twee",
			"having the sickest fixie",
			"having heard about it first",
			"having been into it before it was cool",
			"putting a bird on it",
			"pickling the most things",
			"being the most pedantic",
			"posting the most instagrams",
			"step 1: stealing underwear, step 2: ????, step 3: profit!!",
		]	
	end
end
